my_num: 2
terminate called after throwing an instance of 'std::runtime_error'
  what():  error in network setup: pop-os : Receiving error - 1 : Connection reset by peer
Aborted (core dumped)
